### ISSUE TITLE
I have encountered a fatal error

### ISSUE THREAD

**Issue by ZXStudio** [YihangChen-ee/HAC#2]
![111](https://github.com/YihangChen-ee/HAC/assets/32610605/9b8cc0f0-4faf-44c5-89ba-f9397ad1376a)
![222](https://github.com/YihangChen-ee/HAC/assets/32610605/89f85b2a-5802-49c8-baa0-41a02e437d97)
![333](https://github.com/YihangChen-ee/HAC/assets/32610605/ea1abd9c-a5b3-44a3-b1cb-b9d7fea1240d)
[log.txt](https://github.com/YihangChen-ee/HAC/files/14785776/log.txt)

AssertionError: While the loader support other types, the rest of the code assumes PINHOLE

**Comment by QianyiWu** [comment]
Hi,

Could you check your camera model in cameras.txt? As the current camera model is assumed to be either 'PINHOLE' or 'SIMPLE_PINHOLE' to make sure the splatted 3D Gaussian still has a "Gaussian" shape, we didn't change this part in our HAC but follow the original 3D Gaussian Splatting [design](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/scene/colmap_loader.py#L171). You might also refer to the reason [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/303).

**Comment by YihangChen-ee** [comment]
Hi ZXStudio,

I have noticed Qianyi has answered part of your questions.

I observe another problem from your log.txt file:
''root@autodl-container-5ee0448de2-e336240c:~/HAC-main/data/sparse# python ~/HAC-main/train.py -s ~/HAC-main/data/ -m ~/HAC-main/data/output''
This means you are running the code under the wrong path ''~/HAC-main/data/sparse'' but using a relative path in your command. This may lead to ''FileNotFoundError'' that you have exactly encountered.

To run the code, please refer to the Readme.md where we have clearly presented the running command as ''python run_shell_xxx.py'', where you may need to change the paths and some hyperparameters in the ''run_shell_xxx.py'' for your own data.

I recommend you can firstly try running the provided datasets such as ''MipNeRF360'', and see whether you can run them correctly. After that, you can try your own dataset.

:)

Best

**Comment by ZXStudio** [comment]
> 你好，
> 
> 你能在cameras.txt中检查你的相机型号吗？由于当前的相机模型假设为“PINHOLE”或“SIMPLE_PINHOLE”，以确保喷射的 3D 高斯仍然具有“高斯”形状，因此我们没有在 HAC 中更改这部分，而是遵循原始的 3D 高斯喷射[设计](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/scene/colmap_loader.py#L171)。您也可以参考[这里的](https://github.com/graphdeco-inria/gaussian-splatting/issues/303)原因。

The following is the information in cameras.txt:
#Camera list with one line of data per camera:
#CAMERA-ID, MODEL, WIDTH, HEIGHT, PARAMS
#Number of cameras: 1
1 PINHOLE 8064 4536 5888.7518434988024 5884.369955166248 4032 2268

**Comment by YihangChen-ee** [comment]
Hi ZXStudio,

Thanks for checking your camera type, it seems the camera type is correct.

In this context, I strongly recommend you can firstly try checking your path for running the code, and try running the standard datasets such as "MipNeRF360" (by running `python run_shell_mip360.py ` under the path of `./HAC`.) before running your own data.

You should run the code under the path of `./HAC` but not under `./HAC-main/data/sparse`.
The wrong command path will lead to ''FileNotFoundError''.

:)

**Comment by YihangChen-ee** [comment]
By the way, I notice you do not have an `./images ` directory with should be with the same directory level with the `./sparse ` directory. Please refer to our Readme to see how to prepare your data.

**Comment by ZXStudio** [comment]
> 顺便说一句，我注意到您没有`./images `应该与该目录具有相同目录级别的目录`./sparse `。请参阅我们的自述文件以了解如何准备数据。

按照你的建议, train.py这个脚本运行起来了, 但运行到0% Training progress这步时报错了。错误信息： invalid value for -- gpu architecture (- arch).   我的GPU服务器默认自带cuda 11.8工具。
[log_3.29.txt](https://github.com/YihangChen-ee/HAC/files/14801389/log_3.29.txt)
![system](https://github.com/YihangChen-ee/HAC/assets/32610605/abb6dccd-8289-499e-82a8-ef9ba7daee53)
![目录1](https://github.com/YihangChen-ee/HAC/assets/32610605/0029e336-c89f-4fd9-9eb4-152e541d9898)
![目录2](https://github.com/YihangChen-ee/HAC/assets/32610605/db8ad461-fa78-4a5c-960f-da83dbfd4175)
![目录3](https://github.com/YihangChen-ee/HAC/assets/32610605/c9769c03-0cc8-4096-a4b5-180cabd2283f)

**Comment by YihangChen-ee** [comment]
你好，

我不能确定你的数据是否有问题，但是我真的强烈建议你先在标准的测试数据集上跑起来之后再跑你自己的数据。
因为对于标准的测试数据集，他们的数据格式是肯定正确的，并且我们也提供了现有的脚本，你可以直接跑。
如果标准的测试数据集跑起来了，你再在自己的测试数据集上跑。

根据控制变量法，如果你在标准的测试数据集上也会报这个错误，就说明你的cuda环境有问题，请你检查你的cuda环境。

另：我们是在4090上跑的，我不知道4090D上会不会出问题。

祝好

**Comment by ZXStudio** [comment]
> 你好，
> 
> 我不能确定你的数据是否有问题，但是我真的强烈建议你先在标准的测试数据集上跑起来之后再跑你自己的数据。 因为对于标准的测试数据集，他们的数据格式是肯定正确的，并且我们也提供了现有的脚本，你可以直接跑。 如果标准的测试数据集跑起来了，你再在自己的测试数据集上跑。
> 
> 根据控制变量法，如果你在标准的测试数据集上也会报这个错误，就说明你的cuda环境有问题，请你检查你的cuda环境。
> 
> 另：我们是在4090上跑的，我不知道4090D上会不会出问题。
> 
> 祝好

![公共数据集](https://github.com/YihangChen-ee/HAC/assets/32610605/9a908eea-f072-4567-9fe5-1b395f188356)
我从https://jonbarron.info/mipnerf360/下载了公共数据集解压到了data，然后运行了run_shell_mip360.py，结果报错了。
[Uploading log_3.39_1.txt…]()

**Comment by YihangChen-ee** [comment]
Seems your data path is wrong. Please form your data in the path like this `./data/mipnerf360/bicycle/`, so that you can directly run `python run_shell_mip360.py`. Otherwise you will need to change paths in the `run_shell_mip360.py` script before running it.

Feel free to drop me your WeChat ID via my email: yhchen.ee@sjtu.edu.cn, if you really need help from me to run the code.

**Comment by ZXStudio** [comment]
> Seems your data path is wrong. Please form your data in the path like this `./data/mipnerf360/bicycle/`, so that you can directly run `python run_shell_mip360.py`. Otherwise you will need to change paths in the `run_shell_mip360.py` script before running it.
> 
> Feel free to drop me your WeChat ID via my email: [yhchen.ee@sjtu.edu.cn](mailto:yhchen.ee@sjtu.edu.cn), if you really need my help to run the code.

按照你说的改了目录结构，我还改使用4090显卡，不是之前的4090D。运行python run_shell_mip360.py后，出现了Training progress:   0%|  但报错了：AssertionError: Could not recognize scene type!
[log_3.39_2.txt](https://github.com/YihangChen-ee/HAC/files/14802852/log_3.39_2.txt)

**Comment by ZXStudio** [comment]
> 还是你的路径的问题。你可以在`./scene/__init__.py`的第43行输出一下‘args.source_path’的值，看看和你真正放置‘bicycle’这个文件夹的位置是否一致；你需要注意相对路径和绝对路径的问题。如果你不介意的话，你可以把你的微信号email给我，微信沟通更直接些 👍

我微信号：ZX_Create
