### ISSUE TITLE
如何预览编码后的模型？

### ISSUE THREAD

**Issue by ZXStudio** [YihangChen-ee/HAC#3]
![1](https://github.com/YihangChen-ee/HAC/assets/32610605/2bbaf8ee-6ea6-4477-96a4-812783f19832)
最终产物不应该是一个.ply文件吗？

**Comment by YihangChen-ee** [comment]
Hi,

We losslessly compress the .ply file to ./bitstreams using Arithmetic Coding, which is exactly what our paper does.

Please refer to issue1 and Readme.md to find out more detailed explanations.

THX :)

**Comment by ZXStudio** [comment]
> 和Readme.md

感谢~
