### ISSUE TITLE
Undesirable results when using large datasets

### ISSUE THREAD

**Issue by jxbb233** [YihangChen-ee/HAC#8]
Hi, I tried to train using the kitti360 dataset (>3000 images) and the results don't seem to be very good as shown below. I tried manually adjusting the voxel size and iteration, but not many changes. I feel the problem is that there are not enough Gaussians in the scene to fit the image. Is there any other parameter I can try to adjust? Thanks for your help!
![图片](https://github.com/YihangChen-ee/HAC/assets/75174944/9380b120-79a2-4406-89da-0dce2fe68c9a)

**Comment by YihangChen-ee** [comment]
Hi, Thanks for being interested in our work! I am afraid there are not enough anchors/Gaussians in this scene.
As HAC is built upon Scaffold-GS, have you tried running this dataset using Scaffold-GS?

**Comment by jxbb233** [comment]
It turns out that the problem was caused by an error in our data preprocessing with COLMAP. After switching methods, the issue no longer occurs.
